#HW2

In [ ]:
!wget https://www.dropbox.com/s/0trrbzajj6z09xp/HW2.zip

--2021-06-15 19:29:26--  https://www.dropbox.com/s/0trrbzajj6z09xp/HW2.zip
Resolving www.dropbox.com (www.dropbox.com)... 162.125.5.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.5.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/0trrbzajj6z09xp/HW2.zip [following]
--2021-06-15 19:29:26--  https://www.dropbox.com/s/raw/0trrbzajj6z09xp/HW2.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc923d4e4f900d2532f8a540727d.dl.dropboxusercontent.com/cd/0/inline/BQf-VifuMNZJrRuoMJVM2cnToyp4e33uq_rC5xtgKr9GtmifLJNhtqtJVAAKdKJ5EfhunwCJTOMPgxXPhGlaGouFvSZ_w8vrJUTEYuLQ5DVGbhNct01IWTkMAJsQ2LOH4TbvM5-1LPv00PnlXbaV-Wpe/file# [following]
--2021-06-15 19:29:26--  https://uc923d4e4f900d2532f8a540727d.dl.dropboxusercontent.com/cd/0/inline/BQf-VifuMNZJrRuoMJVM2cnToyp4e33uq_rC5xtgKr9GtmifLJNhtqtJVAAKdKJ5EfhunwCJTOMPgxXPhGlaGouFvSZ_w8vrJUTEYuLQ5

In [ ]:
!unzip HW2.zip

Archive:  HW2.zip
   creating: HW2/
  inflating: HW2/HW2.pdf             
  inflating: HW2/data.csv            
  inflating: HW2/data1.csv           
  inflating: HW2/data2.csv           
  inflating: HW2/data3.csv           
  inflating: HW2/data4.csv           


In [ ]:
%cd HW2

/content/HW2


In [ ]:
!ls

data1.csv  data2.csv  data3.csv  data4.csv  data.csv  HW2.pdf


In [ ]:
import pandas as pd
import numpy as np
from scipy.optimize import minimize

#P1 - MNL Model

#MLE

$max_{\beta}\sum^{T}_{t=1}{logP(j_t|S_t)}$

$\max\sum(\beta_o+\sum\beta_ix_{j_{t}i})-\sum\log(1+\sum{e^{\beta_0+\sum{\beta_i}x_{j_{k}i}}})$

In [ ]:
df = pd.read_csv("data.csv")
df

srch_id  prop_starrating  ...  srch_saturday_night_bool  booking_bool
0             1                4  ...                         1             0
1             1                3  ...                         1             0
2             1                4  ...                         1             0
3             1                4  ...                         1             0
4             1                4  ...                         1             0
...         ...              ...  ...                       ...           ...
153004   665573                4  ...                         0             0
153005   665573                4  ...                         0             0
153006   665573                4  ...                         0             0
153007   665573                4  ...                         0             0
153008   665573                3  ...                         0             0

[153009 rows x 15 columns]

# Normalization

In [ ]:
def normalization(df,names):
  stat_dict = {}
  df_normalized = df.copy()
  for name in names:
    mean = np.array(df_normalized[[name]]).mean()
    std = np.array(df_normalized[[name]]).std()
    df_normalized[[name]] = (df_normalized[[name]]-mean)/std
    stat_dict[name] = (mean,std)

  return df_normalized, stat_dict

In [ ]:
df = df[["srch_id","prop_starrating","prop_review_score","prop_brand_bool","prop_location_score","prop_accesibility_score","prop_log_historical_price","price_usd","promotion_flag","booking_bool"]]
id_set = set(df["srch_id"])
print(id_set)

{1, 622596, 360454, 622603, 524302, 426003, 557077, 131098, 98339, 32807, 360494, 360506, 98364, 393276, 426054, 327751, 655430, 75, 622668, 65614, 65616, 98385, 360530, 524368, 622677, 65626, 426074, 655450, 622688, 655458, 101, 655461, 524395, 655467, 622701, 458865, 655473, 622707, 622708, 622709, 622710, 65656, 622715, 32894, 229510, 524423, 622737, 65682, 32917, 295067, 164000, 622765, 360623, 458927, 590002, 32955, 557247, 295105, 491717, 524486, 295112, 393419, 655566, 262352, 218, 229594, 557276, 98532, 622825, 236, 393456, 557300, 622836, 196854, 622838, 655610, 622851, 622859, 360720, 131350, 655641, 131354, 229662, 622889, 622891, 65839, 360752, 655664, 524595, 426293, 229687, 590137, 622906, 622914, 325, 33095, 328014, 655695, 524624, 590161, 655697, 459091, 622932, 590168, 360796, 655708, 393571, 393575, 491885, 655726, 295282, 622967, 196986, 491904, 426373, 98701, 360853, 131478, 33175, 98713, 459161, 295326, 623006, 623010, 419, 623011, 164261, 98728, 623023, 426422, 16

In [ ]:
names = ["prop_starrating","prop_review_score","prop_brand_bool","prop_location_score","prop_accesibility_score","prop_log_historical_price","price_usd","promotion_flag"]
df_normalized,stat_dict = normalization(df,names)


In [ ]:
stat_dict

{'price_usd': (141.19362259736354, 181.7693498769592),
 'promotion_flag': (0.14480847531844532, 0.3519076310545035),
 'prop_accesibility_score': (0.005993111516316034, 0.07718286163824864),
 'prop_brand_bool': (0.7357279637145527, 0.44094481187898166),
 'prop_location_score': (2.6171728460417363, 1.3481508978402192),
 'prop_log_historical_price': (4.27631054382422, 1.7895033851701312),
 'prop_review_score': (3.9876804632407246, 0.9071191629160908),
 'prop_starrating': (3.157402505734957, 0.8571822862649962)}

In [ ]:
id_set = set(df["srch_id"])

In [ ]:
id_set

{1,
 622596,
 360454,
 622603,
 524302,
 426003,
 557077,
 131098,
 98339,
 32807,
 360494,
 360506,
 98364,
 393276,
 426054,
 327751,
 655430,
 75,
 622668,
 65614,
 65616,
 98385,
 360530,
 524368,
 622677,
 65626,
 426074,
 655450,
 622688,
 655458,
 101,
 655461,
 524395,
 655467,
 622701,
 458865,
 655473,
 622707,
 622708,
 622709,
 622710,
 65656,
 622715,
 32894,
 229510,
 524423,
 622737,
 65682,
 32917,
 295067,
 164000,
 622765,
 360623,
 458927,
 590002,
 32955,
 557247,
 295105,
 491717,
 524486,
 295112,
 393419,
 655566,
 262352,
 218,
 229594,
 557276,
 98532,
 622825,
 236,
 393456,
 557300,
 622836,
 196854,
 622838,
 655610,
 622851,
 622859,
 360720,
 131350,
 655641,
 131354,
 229662,
 622889,
 622891,
 65839,
 360752,
 655664,
 524595,
 426293,
 229687,
 590137,
 622906,
 622914,
 325,
 33095,
 328014,
 655695,
 524624,
 590161,
 655697,
 459091,
 622932,
 590168,
 360796,
 655708,
 393571,
 393575,
 491885,
 655726,
 295282,
 622967,
 196986,
 491904,
 426373,
 

In [ ]:
def rosen(beta):
  beta0 = beta[0]
  beta_rest = beta[1:]
  objective = 0
  for id in id_set:
    temp_matrix = np.array(df_normalized[df_normalized["srch_id"] == id])
    j = np.where(temp_matrix[:,-1] == 1)[0]      
    v_j = temp_matrix[j,1:-1]
    v_p = temp_matrix[:,1:-1]
    if len(v_j) != 0:
      linear = beta0+v_j@beta_rest 
    else:
      linear = 0 
    concave = np.log(np.sum(np.exp(beta0 + v_p@beta_rest))+1)
    T = linear-concave
    # print("T:",T)
    objective = objective + T
  #max -> min
  objective = -objective
  print("objective:",objective)
  print(beta)
  return objective

In [ ]:
beta = np.zeros(9)
# res = minimize(rosen, beta, method='nelder-mead', options={'xatol': 1e-8, 'disp': True})
res = minimize(rosen, beta, method='Powell', options={'xtol': 1e-8, 'disp': True})




objective: [22856.20636359]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
objective: [22856.20636359]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
objective: [24841.66708482]
[1. 0. 0. 0. 0. 0. 0. 0. 0.]
objective: [21185.76279123]
[-1.618034  0.        0.        0.        0.        0.        0.
  0.        0.      ]
objective: [21412.49849843]
[-2.22697946  0.          0.          0.          0.          0.
  0.          0.          0.        ]
objective: [21185.76279123]
[-1.618034  0.        0.        0.        0.        0.        0.
  0.        0.      ]
objective: [21501.40629806]
[-1.00000003  0.          0.          0.          0.          0.
  0.          0.          0.        ]
objective: [21248.04463447]
[-1.38196603  0.          0.          0.          0.          0.
  0.          0.          0.        ]
objective: [21182.73904716]
[-1.70408566  0.          0.          0.          0.          0.
  0.          0.          0.        ]
objective: [21182.46907586]
[-1.68580686  0.          0.          0.       

In [ ]:
beta = res.x
res.x

array([-1.74629566,  0.41212766,  0.1057882 ,  0.1008278 ,  0.02017485,
        0.04341198, -0.06984647, -1.33103003,  0.15948702])

#P2 - Assortment Optimization under MNL

# $max_{S \in \{1,...,n\}} \frac{\sum{p_jv_j}}{1+\sum{v_p}}$

# Key: "nested by price"
compute the assortments ({1},{1,2},{1,2,3}...,{1,2...,n}}) and return the one has best expect revenue

In [ ]:
df1 = pd.read_csv("data1.csv")
df2 = pd.read_csv("data2.csv")
df3 = pd.read_csv("data3.csv")
df4 = pd.read_csv("data4.csv")

In [ ]:
df1 = df1.sort_values(by=['price_usd'], inplace=False,ascending = False)
df2 = df2.sort_values(by=['price_usd'], inplace=False,ascending = False)
df3 = df3.sort_values(by=['price_usd'], inplace=False,ascending = False)
df4 = df4.sort_values(by=['price_usd'], inplace=False,ascending = False)

In [ ]:
names = ["prop_starrating","prop_review_score","prop_brand_bool","prop_location_score","prop_accesibility_score","prop_log_historical_price","price_usd","promotion_flag"]


In [ ]:
def normalization(df,names,stat_dict):
  df_normalized = df.copy()
  for name in names:
    df_normalized[[name]]
    stat_dict[name][0]
    df_normalized[[name]] = (df_normalized[[name]]-stat_dict[name][0])/stat_dict[name][1]

  return df_normalized

In [ ]:
df1_norm = normalization(df1,names,stat_dict)
temp1 = np.array(df1_norm)
v = np.exp(temp1@beta[1:]+beta[0])
length = len(temp1)
exp_list = []
for i in range(length):
  v_temp = v[:i+1]
  temp2 = temp1[:i+1]
  p = temp2[:,-2]
  exp = (p@v_temp)/(1+np.sum(v_temp))
  exp_list.append(exp)
print(exp_list)
print(np.argmax(exp_list))

[0.015454943715396937, 0.026685143782325275, 0.030884641310511402, 0.03230408053935777, 0.03223911598705542, 0.03219399389545412, 0.03149315107161629, 0.030545438094673343, 0.028418751268343628, 0.02399145392290492, 0.020061300202057857, 0.01088139972181752, 0.006723846851611112, 0.002020647182963072, -0.0037111535369017653, -0.009669508187152957, -0.02101559180074713, -0.024283467483204736, -0.028973751083637516, -0.032369773666322, -0.03553658551697022, -0.04430935729354481, -0.04940867344198574, -0.05806851292831452, -0.06317260642696607, -0.06832470132176664, -0.07440069973296654]
3


In [ ]:
end_item = np.argmax(exp_list)
temp1 = np.array(df1_norm)[:end_item+1]
temp1 = np.exp(temp1@beta[1:]+beta[0])
price_unnormalized = np.array(df1['price_usd'])[:end_item+1]
exp_rev = (price_unnormalized@temp1)/(1+np.sum(temp1))
print("expected revenue:",exp_rev)


expected revenue: 65.97394747433725


In [ ]:
df2_norm = normalization(df2,names,stat_dict)
temp1 = np.array(df2_norm)
v = np.exp(temp1@beta[1:]+beta[0])
length = len(temp1)
exp_list = []
for i in range(length):
  v_temp = v[:i+1]
  temp2 = temp1[:i+1]
  p = temp2[:,-2]
  exp = (p@v_temp)/(1+np.sum(v_temp))
  exp_list.append(exp)
print(exp_list)
print(np.argmax(exp_list))

[0.1150710536416566, 0.19598543303955673, 0.22227188427565248, 0.208291920981484, 0.1819122758734124, 0.1656143782472186, 0.15054695409504024, 0.12614047235502893, 0.11121619850460952, 0.09302563705480384, 0.08011489003225897, 0.06522780046295358, 0.05088634205521455, 0.04320059383387433, 0.032333602375522366, 0.02356511076054654, 0.014333112532707417, 0.006313903409329558, -0.0032642832578433935, -0.012618405187641988, -0.02353065224525799, -0.031631075515075935, -0.04255241152782423, -0.047452624798552084, -0.05639154967496053, -0.06105956798480424, -0.07451458364283486, -0.08668822641018056, -0.09302041791514876]
2


In [ ]:
end_item = np.argmax(exp_list)
temp1 = np.array(df2_norm)[:end_item+1]
temp1 = np.exp(temp1@beta[1:]+beta[0])
price_unnormalized = np.array(df2['price_usd'])[:end_item+1]
exp_rev = (price_unnormalized@temp1)/(1+np.sum(temp1))
print("expected revenue:",exp_rev)


expected revenue: 117.30005280995735


In [ ]:
df3_norm = normalization(df3,names,stat_dict)
temp1 = np.array(df3_norm)
v = np.exp(temp1@beta[1:]+beta[0])
length = len(temp1)
exp_list = []
for i in range(length):
  v_temp = v[:i+1]
  temp2 = temp1[:i+1]
  p = temp2[:,-2]
  exp = (p@v_temp)/(1+np.sum(v_temp))
  exp_list.append(exp)
print(exp_list)
print(np.argmax(exp_list))

[0.00868600322407039, 0.07205085954526708, 0.09917555692538417, 0.12639568088363468, 0.14277843678422072, 0.15184057372057969, 0.15664094269087264, 0.16045977479806695, 0.16078919416251677, 0.1468256199386255, 0.13831824484606817, 0.1291724649944679, 0.1196432296968332, 0.11317225778353862, 0.10798129321924302, 0.10075613918790562, 0.09617737569147404, 0.08720748045212193, 0.08014310277277326, 0.07451591499310098, 0.061049402308698326, 0.05080766695694569, 0.044955242965514224, 0.03694796076158019, 0.030821179074270497, 0.02519721684807943]
8


In [ ]:
end_item = np.argmax(exp_list)
temp1 = np.array(df3_norm)[:end_item+1]
temp1 = np.exp(temp1@beta[1:]+beta[0])
price_unnormalized = np.array(df3['price_usd'])[:end_item+1]
exp_rev = (price_unnormalized@temp1)/(1+np.sum(temp1))
print("expected revenue:",exp_rev)


expected revenue: 137.16769498852756


In [ ]:
df4_norm = normalization(df4,names,stat_dict)
temp1 = np.array(df4_norm)
v = np.exp(temp1@beta[1:]+beta[0])
length = len(temp1)
exp_list = []
for i in range(length):
  v_temp = v[:i+1]
  temp2 = temp1[:i+1]
  p = temp2[:,-2]
  exp = (p@v_temp)/(1+np.sum(v_temp))
  exp_list.append(exp)
print(exp_list)
print(np.argmax(exp_list))

[0.06625718165244188, 0.0645188062269149, 0.05294327494575755, 0.012260885664777435, -0.019562460349953237, -0.030106959644949274, -0.04192072159102184, -0.05915319606145994, -0.0715939726879468, -0.0780512506866308, -0.09135607696533676, -0.1104012737013924, -0.12290600109035225, -0.13706939277986302, -0.1449166881784023, -0.16736696310072843, -0.1749428476943746, -0.18272770223137252, -0.19429914985999888, -0.2027927447768341, -0.21428657003356966, -0.22519782318452297, -0.23973544629620752, -0.24836987428188936, -0.2563400240297923, -0.2667684211105749, -0.27658928201539174]
0


In [ ]:
end_item = np.argmax(exp_list)
temp1 = np.array(df4_norm)[:end_item+1]
temp1 = np.exp(temp1@beta[1:]+beta[0])
price_unnormalized = np.array(df4['price_usd'])[:end_item+1]
exp_rev = (price_unnormalized@temp1)/(1+np.sum(temp1))
print("expected revenue:",exp_rev)


expected revenue: 103.69428940132791


#P3 - Pricing under MNL

In [ ]:
beta = np.array([-1.74629566,  0.41212766,  0.1057882 ,  0.1008278 ,  0.02017485,
        0.04341198, -0.06984647, -1.33103003,  0.15948702])

In [ ]:
def normalization(df,names,stat_dict):
  df_normalized = df.copy()
  for name in names:
    df_normalized[[name]]
    stat_dict[name][0]
    df_normalized[[name]] = (df_normalized[[name]]-stat_dict[name][0])/stat_dict[name][1]

  return df_normalized

In [ ]:
price_std = stat_dict["price_usd"][1]
price_mean = stat_dict["price_usd"][0]
print(stat_dict["price_usd"])

(141.19362259736354, 181.7693498769592)


In [ ]:
df1 = pd.read_csv("data1.csv")
df1_norm = normalization(df1,names,stat_dict)

temp1 = np.array(df1_norm)
price = np.array(df1["price_usd"])
def rosen_p3(price):
  temp1[:,-2] = (price-price_mean)/price_std
  obj = -np.log(np.exp(temp1@beta[1:]+beta[0])@(price))+np.log(1+np.sum(np.exp(temp1@beta[1:]+beta[0])))
  return obj
print("price(before opt):",price)
print("rev (before opt):", np.exp(-rosen_p3(price)))
res = minimize(rosen_p3, price, method='nelder-mead', options={"maxiter":100000,'xatol': 1e-8, 'disp': True})
print("price(after opt):",res.x)
print("rev (after opt):", np.exp(-rosen_p3(res.x)))


price(before opt): [150 140 145 125 154 144 131  91  77 107  95  95 108  75 107 131 105 120
 121 147 121 156 147 158 118  99 112]
rev (before opt): 104.64645502489526
Optimization terminated successfully.
         Current function value: -5.174014
         Iterations: 58679
         Function evaluations: 71401
price(after opt): [306.29170099 307.1112147  307.19999404 321.05313564 348.9300244
 302.79266779 315.88236551 304.40737602 262.24884295 272.69179228
 316.98983048 438.15742185 286.26205901 298.73157632 295.41199043
 281.54918471 317.21048016 298.34199324 372.21653887 302.862305
 344.80939718 324.79015278 304.01013728 319.29161045 300.50934767
 325.45090453 319.45684082]
rev (after opt): 176.622292683448


In [ ]:
df2 = pd.read_csv("data2.csv")
df2_norm = normalization(df2,names,stat_dict)
temp1 = np.array(df2_norm)
price = np.array(df2["price_usd"])
# print("price before adjusting:",price)

def rosen_p3(price):
  temp1[:,-2] = (price-price_mean)/price_std
  obj = -np.log(np.exp(temp1@beta[1:]+beta[0])@(price))+np.log(1+np.sum(np.exp(temp1@beta[1:]+beta[0])))
  return obj
print("price(before opt):",price)
print("rev (before opt):", np.exp(-rosen_p3(price)))
res = minimize(rosen_p3, price, method='nelder-mead', options={"maxiter":100000,'xatol': 1e-8, 'disp': True})
print("price(after opt):",res.x)
print("rev (after opt):", np.exp(-rosen_p3(res.x)))

price(before opt): [233 161 123 118 125 102 146 206 212 137 143 110 104 123  86  69  84  84
  73  98 105 147 123 134  73 133  89 117  90]
rev (before opt): 113.43495349835517
Optimization terminated successfully.
         Current function value: -5.493724
         Iterations: 74897
         Function evaluations: 89754
price(after opt): [ 377.13964332  383.15370311 2327.80399516  397.63123536  376.04057226
  377.49397458  368.55587349  376.50191376  384.30649779  389.15632168
  386.83752434  381.45225981  376.86684704  377.79742702  336.13669817
  362.92761153  341.52139754  360.20791414  381.44068841  387.01186484
  378.99121612  366.62279957  365.37291091  362.06709128  397.46506274
  393.22605818  399.55998827  378.77560177  982.82038042]
rev (after opt): 243.16094176326138


In [ ]:
df3 = pd.read_csv("data3.csv")
df3_norm = normalization(df3,names,stat_dict)
temp1 = np.array(df3_norm)
price = np.array(df3["price_usd"])
# print("price before adjusting:",price)

def rosen_p3(price):
  temp1[:,-2] = (price-price_mean)/price_std
  obj = -np.log(np.exp(temp1@beta[1:]+beta[0])@(price))+np.log(1+np.sum(np.exp(temp1@beta[1:]+beta[0])))
  return obj
print("price(before opt):",price)
print("rev (before opt):", np.exp(-rosen_p3(price)))
res = minimize(rosen_p3, price, method='nelder-mead', options={"maxiter":100000,'xatol': 1e-8, 'disp': True})
print("price(after opt):",res.x)
print("rev (after opt):", np.exp(-rosen_p3(res.x)))

price(before opt): [140 211 150 144 191 195 115 281 128 101 138 129 101 180 153 181 171 105
 123 190 101 115 105 603 138 120]
rev (before opt): 118.17868126302996
Optimization terminated successfully.
         Current function value: -5.113908
         Iterations: 41286
         Function evaluations: 50461
price(after opt): [ 319.93718262  312.82528634 7381.88414231  300.13716184  287.82090883
  296.56438697  284.73530159  291.66729697  305.02328646  266.09216996
  317.19791132 2147.09468717  293.99082751  302.47969295  291.76309612
  306.02266506  303.14095813  275.85877444 5156.9634577   314.78605697
  313.41863969  305.67919173  286.58865356  260.00993214  291.51390129
  293.15809886]
rev (after opt): 166.31906409777085


In [ ]:
df4 = pd.read_csv("data4.csv")
df4_norm = normalization(df4,names,stat_dict)
temp1 = np.array(df4_norm)
price = np.array(df4["price_usd"])
# print("price before adjusting:",price)

def rosen_p3(price):
  temp1[:,-2] = (price-price_mean)/price_std
  obj = -np.log(np.exp(temp1@beta[1:]+beta[0])@(price))+np.log(1+np.sum(np.exp(temp1@beta[1:]+beta[0])))
  return obj
print("price(before opt):",price)
print("rev (before opt):", np.exp(-rosen_p3(price)))
res = minimize(rosen_p3, price, method='nelder-mead', options={"maxiter":100000,'xatol': 1e-8, 'disp': True})
print("price(after opt):",res.x)
print("rev (after opt):", np.exp(-rosen_p3(res.x)))

price(before opt): [ 71  45  92 152 195  45 105  85 100  82 105  49  68  56  64 106  52  40
 105 112 140 114  51  86  48  50 110]
rev (before opt): 78.79187938101204
Optimization terminated successfully.
         Current function value: -5.342554
         Iterations: 39522
         Function evaluations: 48238
price(after opt): [ 334.82051222  370.93280165  342.43030503  344.41264038  341.44629708
  337.73593201  340.95974878  349.90222301  345.02828272  349.31436818
  344.79967803  358.20664198  341.29781343  345.87541748  379.37211585
  352.30302937  326.55978246  344.95185223 1387.90638077  346.57684417
 2641.08316086  340.47300798  336.92835264  347.31140909  369.88052536
  339.13575031  346.97392473]
rev (after opt): 209.04584800953765


#P4 - Mixture of MNL

In [ ]:

def normalization_4(df,names):
  stat_dict = {}
  df_normalized = df.copy()
  for name in names:
    mean = np.array(df_normalized[[name]]).mean()
    std = np.array(df_normalized[[name]]).std()
    df_normalized[[name]] = (df_normalized[[name]]-mean)/std
    stat_dict[name] = (mean,std)

  return df_normalized, stat_dict

df_total = pd.read_csv("data.csv")

df_early = df_total[df_total["srch_booking_window"] >= 7]
df_late = df_total[df_total["srch_booking_window"] < 7]

df_early = df_early[["srch_id","prop_starrating","prop_review_score","prop_brand_bool","prop_location_score","prop_accesibility_score","prop_log_historical_price","price_usd","promotion_flag","booking_bool"]]
id_set_early = set(df_early["srch_id"])

df_late = df_late[["srch_id","prop_starrating","prop_review_score","prop_brand_bool","prop_location_score","prop_accesibility_score","prop_log_historical_price","price_usd","promotion_flag","booking_bool"]]
id_set_late = set(df_late["srch_id"])

names = ["prop_starrating","prop_review_score","prop_brand_bool","prop_location_score","prop_accesibility_score","prop_log_historical_price","price_usd","promotion_flag"]
df_normalized_late,stat_dict_late = normalization_4(df_late,names)
df_normalized_early,stat_dict_early = normalization_4(df_early,names)

In [ ]:
df_total = pd.read_csv("data.csv")
early_counter = 0
late_counter = 0
for id in id_set:
  time = np.array(df_total[df_total["srch_id"] == id]["srch_booking_window"])[0]
  if time <7:
    late_counter = late_counter +1
  else:
    early_counter = early_counter +1 

In [ ]:
theta_late = late_counter/(late_counter+early_counter)
theta_early = early_counter/(late_counter+early_counter)
print(theta_late,theta_early)
df_normalized,stat_dict = normalization(df,names)

0.45690687096001914 0.5430931290399809


In [ ]:
def rosen_p4_late(beta):
  beta0 = beta[0]
  beta_rest = beta[1:]
  objective = 0
  for id in id_set_late:
    temp_matrix = np.array(df_normalized_late[df_normalized_late["srch_id"] == id])
    j = np.where(temp_matrix[:,-1] == 1)[0]      
    v_j = temp_matrix[j,1:-1]
    v_p = temp_matrix[:,1:-1]
    if len(v_j) != 0:
      linear = beta0+v_j@beta_rest 
    else:
      linear = 0 
    concave = np.log(np.sum(np.exp(beta0 + v_p@beta_rest))+1)
    T = linear-concave
    # print("T:",T)
    objective = objective + T
  #max -> min
  objective = -objective
  print("objective:",objective)
  print(beta)
  return objective


def rosen_p4_early(beta):
  beta0 = beta[0]
  beta_rest = beta[1:]
  objective = 0
  for id in id_set_early:
    temp_matrix = np.array(df_normalized_early[df_normalized_early["srch_id"] == id])
    j = np.where(temp_matrix[:,-1] == 1)[0]      
    v_j = temp_matrix[j,1:-1]
    v_p = temp_matrix[:,1:-1]
    if len(v_j) != 0:
      linear = beta0+v_j@beta_rest 
    else:
      linear = 0 
    concave = np.log(np.sum(np.exp(beta0 + v_p@beta_rest))+1)
    T = linear-concave
    # print("T:",T)
    objective = objective + T
  #max -> min
  objective = -objective
  print("objective:",objective)
  print(beta)
  return objective

In [ ]:
beta_early = np.array([-1.74629566,  0.41212766,  0.1057882 ,  0.1008278 ,  0.02017485,
        0.04341198, -0.06984647, -1.33103003,  0.15948702])

res_early = minimize(rosen_p4_early, beta_early, method='Powell', options={'xtol': 0.0001,'disp': True})
res_early.x


objective: [11069.83305377]
[-1.74629566  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [11069.83305377]
[-1.74629566  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [11552.95536386]
[-0.74629566  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [11992.05930484]
[-3.36432966  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [11069.83305377]
[-1.74629566  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [11139.66832284]
[-2.36432963  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [11178.04376466]
[-1.36432966  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [11057.13810574]

array([-1.92938236,  0.38149619,  0.12248097,  0.09441839, -0.02216229,
        0.05911702, -0.09687283, -1.30946845,  0.14093324])

In [ ]:
beta_late = np.array([-1.74629566,  0.41212766,  0.1057882 ,  0.1008278 ,  0.02017485,
        0.04341198, -0.06984647, -1.33103003,  0.15948702])

beta_late = minimize(rosen_p4_late, beta_late, method='Powell', options={'xtol': 0.0001,'disp': True})
beta_late.x

objective: [9548.44002366]
[-1.74629566  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [9548.44002366]
[-1.74629566  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [9708.38634719]
[-0.74629566  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [10684.6740154]
[-3.36432966  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [9548.44002366]
[-1.74629566  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [9752.04268184]
[-2.36432963  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [9546.47240431]
[-1.36432966  0.41212766  0.1057882   0.1008278   0.02017485  0.04341198
 -0.06984647 -1.33103003  0.15948702]
objective: [9536.61265782]
[-1.547

array([-1.5123098 ,  0.45373342,  0.09951058,  0.10921596,  0.08693429,
        0.02492945, -0.02869543, -1.06396349,  0.18260161])